models/slider.py
from typing import Dict
from pydantic import BaseModel, Field

from models.database import *

slider_collection = database["slider"]
slider_directory = "Slider"


class SliderLang(BaseModel):
    text: str = "TastyBites"


class Slider(BaseModel):
    id: int = Field(None, alias="_id")

    image: str = f"objects/{slider_directory}/default.jpg"
    language: Dict[str, SliderLang] = {"uk": SliderLang(), "en": SliderLang()}

    isShow: bool = True

    def from_form(self, form, image):

        if image:
            self.image = save_image(image, slider_directory, self.id)

        self.language = {
            "uk": SliderLang(text=form["uk_text"]),
            "en": SliderLang(text=form["en_text"]),
        }
        self.isShow = form["isShow"]

        return self

    def save(self):
        if document_by_id(slider_collection, self.id):
            slider_collection.replace_one({"_id": self.id}, self.dict(by_alias=True))
        else:
            self.id = new_document_id(slider_collection)
            slider_collection.insert_one(self.dict(by_alias=True))

    def delete(self):
        delete_image(slider_directory, self.id)
        slider_collection.delete_one({"_id": self.id})

routes/admin.py
import datetime

from flask import (
    Blueprint,
    Response,
    redirect,
    render_template,
    request,
    flash,
    url_for,
    jsonify,
)
from flask_login import (
    login_required,
    current_user,
    LoginManager,
    login_user,
    logout_user,
)

from werkzeug.security import check_password_hash
import re

from models.database import admin_by_username, document_by_codename
from models.dish import (
    Dish,
    DishCategory,
    CategoryType,
    dish_category_type_collection,
    dish_category_collection,
    ENCategoryType,
    dish_collection,
)
from models.admin import Admin, admin_collection
from models.order import Order, Status, order_collection
from models.reservation import Reservation, reservation_collection
from models.settings import Settings, settings_collection
from models.slider import Slider, slider_collection
from models.announce import Announce, announce_collection, document_by_id


login_manager = LoginManager()
login_manager.login_view = "admin.login"

admin_router = Blueprint("admin", __name__)


@admin_router.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect("/admin")

    if request.method == "POST":
        check_admin = admin_by_username(admin_collection, request.form["username"])
        if check_admin:
            if check_password_hash(check_admin["password"], request.form["password"]):
                check_admin = Admin(**check_admin)
                login_user(check_admin)
                return redirect(url_for("admin.admin_main"))
            else:
                flash("Password is invalid!")
                return redirect(url_for("admin.login"))
        else:
            flash("Undefined Login")
            return redirect(url_for("admin.login"))
    else:
        return render_template("admin/login.html")


@admin_router.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect("/")


@login_manager.user_loader
def load_user(userid):
    admin = document_by_id(admin_collection, int(userid))
    if admin is None:
        return redirect(url_for("admin.login"))
    return Admin(**admin)


@admin_router.route("/", methods=["GET", "POST"])
@login_required
def admin_main():
    return redirect(url_for("admin.dish_categories"))


@admin_router.route("/dishes", methods=["GET", "POST"])
@login_required
def dish_categories():
    if request.method == "POST":
        print("CALL1")

        form = request.form.to_dict()

        form["code_name"] = re.sub(" +", " ", form["code_name"])
        form["code_name"] = form["code_name"].strip()
        form["code_name"] = form["code_name"].replace(" ", "_")

        form["isShow"] = True if form["isShow"] == "on" else False
        DishCategory().from_form(form).save()

        return redirect(url_for("admin.dish_categories"))

    else:
        print("CALL2")

        data = [
            DishCategory(**category).to_dict
            for category in dish_category_collection.find()
        ]

        types = list(dish_category_type_collection.find())

        # types = ["Restaraunt", "Banquet", "Souvenirs", "Food", "VineCard", "Drinks"]

        return render_template(
            "admin/dishes/dishCategories.html", data=data, types=types
        )


@admin_router.route("/dishes/create", methods=["GET", "POST"])
@login_required
def create_dish():
    if request.method == "POST":
        form = request.form.to_dict()

        form["code_name"] = re.sub(" +", " ", form["code_name"])
        form["code_name"] = form["code_name"].strip()
        form["code_name"] = form["code_name"].replace(" ", "_")

        form["isShow"] = True if form["isShow"] == "on" else False

        Dish().from_form(form, request.files.get("image")).save()

        return redirect(
            url_for(
                "admin.dishes",
                category_code=dish_category_collection.find_one(
                    {"_id": int(form["category"])}
                )["code_name"],
            )
        )

    else:
        return render_template(
            "admin/dishes/addDish.html",
            data=list(dish_category_collection.find()),
            types=list(dish_category_type_collection.find()),
        )


@admin_router.route("/dishes/<category_code>", methods=["GET", "POST"])
@login_required
def dishes(category_code):
    dish_category = document_by_codename(dish_category_collection, category_code)
    if dish_category is None:
        return redirect(url_for("admin.dish_categories"))
    dish_category = DishCategory(**dish_category)

    if request.method == "POST":
        if request.form["_method"] == "PUT":

            form = request.form.to_dict()
            form["isShow"] = True if form["isShow"] == "on" else False
            dish_category.from_form(form).save()

            return redirect(url_for("admin.dish_categories"))

        elif request.form["_method"] == "DELETE":
            dish_category.delete()
            return redirect(url_for("admin.dish_categories"))
    else:
        return render_template(
            "admin/dishes/dishes.html",
            data=list(
                dish_collection.find(
                    {"category": dish_category.id},
                    {
                        "category": False,
                        "image": False,
                        "language.en": False,
                        "language.uk.description": False,
                    },
                )
            ),
            types=list(dish_category_type_collection.find()),
        )


@admin_router.route("/dishes/<category_code>/<dish_code>", methods=["GET", "POST"])
@login_required
def dish(category_code, dish_code):
    dish = document_by_codename(dish_collection, dish_code)
    if dish is None:
        return redirect(url_for("admin.dish_categories"))
    dish = Dish(**dish)

    if request.method == "POST":
        if request.form["_method"] == "PUT":
            form = request.form.to_dict()
            form["isShow"] = True if form["isShow"] == "on" else False

            dish.from_form(form, request.files.get("image")).save()

        elif request.form["_method"] == "DELETE":
            dish.delete()

        return redirect(url_for("admin.dishes", category_code=category_code))
    else:
        return render_template(
            "admin/dishes/editDish.html",
            data=dish.dict(),
            data_categories=list(dish_category_collection.find()),
        )


@admin_router.route("/orders", methods=["GET", "POST"])
@login_required
def orders():
    if request.method == "POST":
        pass
    else:
        return render_template(
            "admin/orders/orders.html",
            data=list(
                order_collection.find(
                    {},
                    {
                        "cart": False,
                        "client_email": False,
                        "client_comment": False,
                        "street": False,
                        "house": False,
                        "flat": False,
                        "porch": False,
                        "sentAt": False,
                    },
                )
            ),
        )


@admin_router.route("/orders/<int:orderID>", methods=["GET", "POST"])
@login_required
def order(orderID):
    order = document_by_id(order_collection, orderID)
    if order is None:
        return redirect(url_for("admin.orders"))
    order = Order(**order)

    if request.method == "POST":
        if request.form["_method"] == "DELETE":
            order.delete()
        else:
            form = request.form.to_dict()
            order.status = form["status"]
            order.save()

        return redirect(url_for("admin.orders"))
    else:
        return render_template(
            "admin/orders/infoOrder.html",
            data=order.dict(),
            data_statuses=Status.list(),
            dishes=list(dish_collection.find()),
        )


@admin_router.route("/reservations", methods=["GET", "POST", "PUT", "DELETE"])
@login_required
def reservations():
    return render_template(
        "admin/reservations/reservations.html",
        data=list(reservation_collection.find()),
    )


@admin_router.route(
    "/reservations/<int:reservationID>", methods=["GET", "POST", "PUT", "DELETE"]
)
@login_required
def reservation(reservationID):
    reserve = document_by_id(reservation_collection, reservationID)
    if reserve is None:
        return redirect(url_for("admin.reservations"))
    reserve = Reservation(**reserve)

    if request.method == "POST":
        if request.form["_method"] == "DELETE":
            reserve.delete()
        else:
            form = request.form.to_dict()
            reserve.isAccepted = True if form["isAccepted"] == "on" else False
            reserve.save()

        return redirect(url_for("admin.reservations"))
    else:
        return render_template(
            "admin/reservations/infoReservation.html", data=reserve.dict()
        )


@admin_router.route("/sliders/create", methods=["GET", "POST"])
@login_required
def create_slider():
    if request.method == "POST":
        form = request.form.to_dict()
        form["isShow"] = True if form["isShow"] == "on" else False
        Slider().from_form(form, request.files.get("image")).save()

        return redirect(url_for("admin.sliders"))
    else:
        return render_template("admin/sliders/addSlider.html")


@admin_router.route("/sliders", methods=["GET"])
@login_required
def sliders():
    if request.method == "GET":
        return render_template(
            "admin/sliders/sliders.html",
            data=list(slider_collection.find({}, {"image": False})),
        )


@admin_router.route("/sliders/<int:sliderID>", methods=["GET", "POST", "PUT", "DELETE"])
@login_required
def slider(sliderID):
    slider = document_by_id(slider_collection, sliderID)
    if slider is None:
        return redirect(url_for("admin.sliders"))
    slider = Slider(**slider)

routes/website.py
from flask import (
    Blueprint,
    Response,
    redirect,
    render_template,
    request,
    flash,
    url_for,
    g,
    session,
)
from flask_cors import cross_origin
import ast

from models.database import document_by_id
from models.dish import Dish, DishCategory, CategoryType, dish_collection, dish_category_type_collection, \
    dish_category_collection
from models.order import Order, order_collection
from models.reservation import Reservation
from models.settings import Settings, settings_collection
from models.slider import Slider, slider_collection
from models.announce import Announce, announce_collection
from routes.errors import page_not_found
from api.bot import (
    new_reservation,
    new_order
)

website_router = Blueprint("website", __name__)


@website_router.route("/change_lang", methods=["GET", "POST"])
def change_lang():
    if request.method == "POST":
        session["lang"] = request.form["lang"]
        return redirect(request.referrer)
    else:
        return redirect(request.referrer)


@website_router.route("/", methods=["GET"])
def index():
    return render_template(
        "website/index.html",
        categories=list(dish_category_collection.find({'isShow': True})),
        slider=list(slider_collection.find({'isShow': True})),
        info=document_by_id(settings_collection, 1),
        dishes=list(dish_collection.find({'isShow': True}))
    )


@website_router.route("/announces", methods=["GET"])
def announces():
    return render_template(
        "website/announce.html",
        categories=list(dish_category_collection.find({'isShow': True})),
        announce=list(announce_collection.find({'isShow': True})),
        info=document_by_id(settings_collection, 1),
        dishes=list(dish_collection.find({'isShow': True}))
    )


@website_router.route("/delivery", methods=["GET"])
def delivery():
    return render_template(
        "website/delivery.html",
        info=document_by_id(settings_collection, 1),
        categories=list(dish_category_collection.find({'isShow': True})),
        types=list(dish_category_type_collection.find()),
        dishes=list(dish_collection.find({'isShow': True}))
    )


@website_router.route("/menu", methods=["GET"])
def menu():
    return render_template(
        "website/menu.html",
        info=document_by_id(settings_collection, 1),
        categories=list(dish_category_collection.find({'isShow': True})),
        types=list(dish_category_type_collection.find()),
        dishes=list(dish_collection.find({'isShow': True}))
    )


@website_router.route("/reserve", methods=["POST"])
@cross_origin()
def reserve():
    form = request.form.to_dict()
    new_reservation(form)
    Reservation().from_form(form).save()

    return redirect(request.referrer)


@website_router.route("/order", methods=["POST"])
@cross_origin()
def order():
    form = request.form.to_dict()

    _order = Order().from_form(form)
    _order.save()

    new_order(request.form.to_dict())

    return redirect(
        url_for(
            "website.order_id",
            order_id=_order.id)
    )


@website_router.route("/order/<order_id>", methods=["GET"])
@cross_origin()
def order_id(order_id):
    order = document_by_id(order_collection, int(order_id))
    keys_to_delete = ["client_email", "client_name", "client_phone"]
    for key in keys_to_delete:
        del order[key]
    if order:
        return render_template(
            "website/order.html",
            info=document_by_id(settings_collection, 1),
            order=order,
            categories=list(dish_category_collection.find()),
            types=list(dish_category_type_collection.find()),
            dishes=list(dish_collection.find())
        )

    return redirect(request.referrer)


@website_router.route("/holl/<code_name>", methods=["GET"])
def holl(code_name):
    try:
        return render_template(
            "website/holl.html",
            info=document_by_id(settings_collection, 1),
            categories=list(dish_category_collection.find({'isShow': True})),
            types=list(dish_category_type_collection.find()),
            dishes=list(dish_collection.find({'isShow': True})),
            target_holl=code_name
        )
    except:
        return page_not_found("e")


@website_router.route("/shop", methods=["GET"])
def shop():
    return render_template(
        "website/shop.html",
        info=document_by_id(settings_collection, 1),
        categories=list(dish_category_collection.find({'isShow': True})),
        types=list(dish_category_type_collection.find()),
        dishes=list(dish_collection.find({'isShow': True})),
    )


@website_router.route("/contacts", methods=["GET"])
def contacts():
    return render_template(
        "website/contacts.html",
        info=document_by_id(settings_collection, 1),
        dishes=list(dish_collection.find({'isShow': True})),
        categories=list(dish_category_collection.find({'isShow': True})),
    )

# @website_router.route("/alt_menu", methods=["GET"])
# def alt_menu():
#     return render_template(
#         "website/alt_menu.html",
#         info=document_by_id(settings_collection, 1),
#         dishes=list(dish_collection.find({'isShow': True}))
#     )

templates/includes/footer.html
<footer>
    <div class="footer-cantainer-1">
        <div class="schedule">
            <i class="material-icons">watch_later</i>
            <p>{{ _('Пн') }} {{ info['monday_time'] }}</p>
            <p>{{ _('Вт') }} - {{ _('Нд') }} {{ info['other_days_time'] }}</p>
        </div>
        <div class="address">
            <i class="material-icons">location_on</i>
            <p>{{ g.locale['address'] }}</p>
        </div>
    </div>
    </div>
    <div class="footer-cantainer-2">
        <div>
            <h3>{{g.locale['name'] }}</h3>
        </div>
        <div>
            <span>
                <a href="{{ info['instagram'] }}" title="Instagram">
                    <svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#clip0)">
                            <path
                                d="M14.8077 0H6.73077C3.01404 0 0 3.01404 0 6.73077V14.8077C0 18.5244 3.01404 21.5385 6.73077 21.5385H14.8077C18.5244 21.5385 21.5385 18.5244 21.5385 14.8077V6.73077C21.5385 3.01404 18.5244 0 14.8077 0ZM19.5192 14.8077C19.5192 17.4058 17.4058 19.5192 14.8077 19.5192H6.73077C4.13269 19.5192 2.01923 17.4058 2.01923 14.8077V6.73077C2.01923 4.13269 4.13269 2.01923 6.73077 2.01923H14.8077C17.4058 2.01923 19.5192 4.13269 19.5192 6.73077V14.8077Z" />
                            <path
                                d="M10.7693 5.38461C7.79561 5.38461 5.38464 7.79557 5.38464 10.7692C5.38464 13.7429 7.79561 16.1538 10.7693 16.1538C13.7429 16.1538 16.1539 13.7429 16.1539 10.7692C16.1539 7.79557 13.7429 5.38461 10.7693 5.38461ZM10.7693 14.1346C8.91426 14.1346 7.40387 12.6242 7.40387 10.7692C7.40387 8.91288 8.91426 7.40384 10.7693 7.40384C12.6243 7.40384 14.1346 8.91288 14.1346 10.7692C14.1346 12.6242 12.6243 14.1346 10.7693 14.1346Z" />
                            <path
                                d="M16.5577 5.69821C16.954 5.69821 17.2752 5.37698 17.2752 4.98071C17.2752 4.58445 16.954 4.26321 16.5577 4.26321C16.1614 4.26321 15.8402 4.58445 15.8402 4.98071C15.8402 5.37698 16.1614 5.69821 16.5577 5.69821Z" />
                        </g>
                        <defs>
                            <clipPath id="clip0">
                                <rect width="21.5385" height="21.5385" fill="white" />
                            </clipPath>
                        </defs>
                    </svg>
                </a>
            </span>
            <span>
                <a href="{{ info['facebook'] }}" title="Facebook">
                    <svg width="12" height="22" viewBox="0 0 12 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M7.2077 7.40385V4.71154C7.2077 3.96846 7.81078 3.36538 8.55385 3.36538H9.90001V0H7.2077C4.97712 0 3.16924 1.80788 3.16924 4.03846V7.40385H0.476929V10.7692H3.16924V21.5385H7.2077V10.7692H9.90001L11.2462 7.40385H7.2077Z" />
                    </svg>
                </a>
            </span>
            <span>
                <a href="{{ info['tiktok'] }}" title="Tik tok">
                    <svg width="20" height="22" viewBox="0 0 20 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path
                            d="M19.2058 5.40103C17.9766 5.40103 16.8425 4.99382 15.9317 4.30686C14.8872 3.51936 14.1367 2.3642 13.8717 1.03276C13.806 0.703798 13.7707 0.364315 13.7673 0.0164185H10.256V9.61113L10.2518 14.8666C10.2518 16.2716 9.33681 17.463 8.06848 17.882C7.70039 18.0036 7.30286 18.0612 6.88891 18.0385C6.36055 18.0094 5.86542 17.85 5.43507 17.5926C4.51926 17.0448 3.89835 16.0512 3.88152 14.9146C3.85502 13.1381 5.2912 11.6897 7.06644 11.6897C7.41686 11.6897 7.7534 11.7469 8.06848 11.8508V9.22832V8.28559C7.73615 8.23637 7.39793 8.21071 7.05592 8.21071C5.11283 8.21071 3.29552 9.0184 1.99649 10.4735C1.01463 11.5732 0.425692 12.9761 0.334826 14.4472C0.215776 16.3798 0.922927 18.2168 2.29432 19.5723C2.49582 19.7712 2.70742 19.9559 2.9287 20.1263C4.10448 21.0311 5.54192 21.5216 7.05592 21.5216C7.39793 21.5216 7.73615 21.4964 8.06848 21.4472C9.48278 21.2377 10.7877 20.5903 11.8175 19.5723C13.0829 18.3216 13.7821 16.6612 13.7896 14.8939L13.7715 7.04587C14.3752 7.51155 15.0352 7.89689 15.7437 8.19599C16.8454 8.66083 18.0136 8.89641 19.2159 8.89599V6.34629V5.40019C19.2167 5.40103 19.2066 5.40103 19.2058 5.40103Z" />
                    </svg>
                </a>
            </span>
        </div>
    </div>
    <div class="footer-cantainer-3">
        <div class="phone">
            <i class="material-icons">phone</i>
            <p><a href="tel:{{ info['phone_1'] }}">{{ info['phone_1'] }}</a></p>
            <p><a href="tel:{{ info['phone_2'] }}">{{ info['phone_2'] }}</a></p>
        </div>
        <div class="email">
            <i class="material-icons">mail</i>
            <p><a href="mailto:{{ info['email'] }}">{{ info['email'] }}</a></p>
        </div>
    </div>
</footer>

templates/includes/menu.html
<section>
    <div class="page-title">
        <div class="menu-title">
            {% if target_holl != 'children_room' %}
                <span data-filter=".type-id-{{ types[3]['_id'] }}">
                    {{ types[3][g.locale+'_type'] }}
                </span>
                <span data-filter=".type-id-{{ types[4]['_id'] }}">
                    {{ types[4][g.locale+'_type'] }}
                </span>
                <span data-filter=".type-id-{{ types[5]['_id'] }}">
                    {{ types[5][g.locale+'_type'] }}
                </span>
            {% else %}
            {% for category in categories %}
            {% if 7 in category['type'] %}
            <span data-filter=".category-{{ category['language'][g.locale]['name'] }}">
                {{ category['language'][g.locale]['name'] }}
            </span>
            {% endif %}
            {% endfor %}
            {% endif %}
        </div>
    </div>
        <div class="row menu-container">
            {% for category in categories %}
            {% if category["count"] != 0 %}
            <div class="col s12 m6 mix {% for categ in category['type'] %}type-id-{{ categ }} {% endfor %}">
                <h4>{{ category['language'][g.locale]['name'] }}</h4>
                <div class="row">
                    {% for item in dishes %}
                        {% if item['category'] == category['_id'] %}
                            <div class="col s7">
                                <p class="name">{{ item['language'][g.locale]['name'] }}</p>
                                <p>({{ item['language'][g.locale]['ingredients'] }})</p>
                            </div>
                            <div class="col s5 center-align">
                                <span>{{ item['weight'] }} {{_("г")}} |  {{ item['price'] }} {{_("GBP")}}</span>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
</section>

templates/includes/navbar.html
<header class="navbar">
    <nav>
        <div class="nav-wrapper">
            <a href="/" class="brand-logo left">
                <img class="responsive-img" src="{{ url_for('static', filename='images/logo.svg') }}" alt="">
                <h3>{{ info['language'][g.locale]['name'] }}</h3>
            </a>
            {% set url = request.url %}
            <ul class="right hide-on-med-and-down">
                <li>
                    <a href="{{ url_for('website.index') }}" {% if 'delivery' not in url and 'menu' not in url
                        and 'team' not in url and 'holl' not in url %}class="active" {% endif %}>{{_("Головна")}}</a>
                </li>
                <li>
                    <a href="{{ url_for('website.menu') }}" {% if 'menu' in url %}class="active" {% endif
                        %}>{{_("Меню")}}</a>
                </li>
                <li>
                    <a href="{{ url_for('website.holl', code_name='ribs_holl') }}" {% if 'ribs_holl' in url %}class="active"
                        {% endif %}>{{_("Реберня")}}</a>
                </li>
                <!-- <li>
                    <a href="{{ url_for('website.shop') }}" {% if 'shop' in url %}class="active"
                        {% endif %}>{{_("Крамниця")}}</a>
                </li> -->
                <li>

                    <a href="{{ url_for('website.delivery') }}" {% if 'delivery' in url %}class="active" {% endif
                        %}>{{_("Доставка їжі")}}</a>
                </li>
                <li>
                    <a href="{{ url_for('website.announces') }}" {% if 'team' in url %}class="active" {% endif
                        %}>{{_("Анонси")}}</a>
                </li>
                <li>
                    <a href="{{ url_for('website.contacts') }}" {% if 'contacts' in url %}class="active" {% endif
                        %}>{{_("Контакти")}}</a>
                </li>
                <li>
                    <a class="modal-trigger" href="#modal_reserve">{{_("Забронювати")}}</a>
                </li>
                <li>
                    <a class="modal-trigger" href="#modal_cart" id="cart" onclick="checkCart()">
                    </a>
                </li>
                <!-- <li>
                    <form action="{{ url_for('website.change_lang') }}" method="POST">
                        {% if g.locale == "en" %}
                        <input type="hidden" name="lang" value="uk">
                        <button type="submit"><b>UK</b></button>
                        {% else %}
                        <input type="hidden" name="lang" value="en">
                        <button type="submit"><b>EN</b></button>
                        {% endif %}
                    </form>
                </li> -->
            </ul>
            <div class="menu-cart">
                <a class="modal-trigger" href="#modal_cart" id="cart-mob" onclick="checkCart()">
                </a>
                <a href="#" data-target="mobile" class="sidenav-trigger">
                    <i class="material-icons">menu</i>
                </a>
            </div>
        </div>
    </nav>
</header>

<ul class="sidenav" id="mobile">
    <i class="material-icons close" onclick="$('#mobile').sidenav('close');">close</i>
    <li>
        <a href="{{ url_for('website.index') }}" {% if 'delivery' not in url and 'menu' not in url
        and 'team' not in url and 'holl' not in url %}class="active" {% endif %}>{{_("Головна")}}</a>
    </li>
    <li>
        <a href="{{ url_for('website.menu') }}" {% if 'menu' in url %}class="active" {% endif
            %}>{{_("Меню")}}</a>
    </li>
    <li>
        <a href="{{ url_for('website.holl', code_name='ribs_holl') }}" {% if 'ribs_holl' in url %}class="active"
        {% endif %}>{{_("Реберня")}}</a>
    </li>
 <li>
        <a href="{{ url_for('website.shop') }}" {% if 'shop' in url %}class="active"
        {% endif %}>{{_("Крамниця")}}</a>
    </li>    
    <li>

        <a href="{{ url_for('website.delivery') }}" {% if 'delivery' in url %}class="active" {% endif
            %}>{{_("Доставка їжі")}}</a>
    </li>
    <li>
        <a href="{{ url_for('website.announces') }}" {% if 'team' in url %}class="active" {% endif
            %}>{{_("Анонси")}}</a>
    </li>
    <li>
        <a href="{{ url_for('website.contacts') }}" {% if 'contacts' in url %}class="active" {% endif
            %}>{{_("Контакти")}}</a>
    </li>
    <li>
        <a class="modal-trigger" href="#modal_reserve">{{_("Забронювати")}}</a>
    </li>
    <li>
        <form action="{{ url_for('website.change_lang') }}" method="POST">
            {% if g.locale == "en" %}
            <input type="hidden" name="lang" value="uk">
            <button type="submit"><b>UK</b></button>
            {% else %}
            <input type="hidden" name="lang" value="en">
            <button type="submit"><b>EN</b></button>
            {% endif %}
        </form>
    </li>
</ul>

templates/includes/sidebar.html
<div class="sidebar">
    <h2>Area 51</h2>
    {% set url = request.url %}
    <ul>
        <li>
            <a class="{% if 'dish' in url %}active{% endif %}" href="{{ url_for('admin.dish_categories') }}">
                <i class="material-icons prefix">restaurant</i>
                Dishes
            </a>
        </li>
        <li>
            <a class="{% if 'orders' in url %}active{% endif %}" href="{{ url_for('admin.orders') }}">
                <i class="material-icons prefix">assignment</i>
                Orders
            </a>
        </li>
        <li>
            <a class="{% if 'reservations' in url %}active{% endif %}" href="{{ url_for('admin.reservations') }}">
                <i class="material-icons prefix">restore</i>
                Reservations
            </a>
        </li>
        <li>
            <a class="{% if 'sliders' in url %}active{% endif %}" href="{{ url_for('admin.sliders') }}">
                <i class="material-icons prefix">slideshow</i>
                Slider
            </a>
        </li>
        <li>
            <a class="{% if 'announces' in url %}active{% endif %}" href="{{ url_for('admin.announces') }}">
                <i class="material-icons prefix">supervised_user_circle</i>
                Announces
            </a>
        </li>
        <li>
            <a class="{% if 'admins' in url %}active{% endif %}" href="{{ url_for('admin.admins') }}">
                <i class="material-icons prefix">people</i>
                Admins
            </a>
        </li>
        <li>
            <a class="{% if 'settings' in url %}active{% endif %}" href="{{ url_for('admin.settings') }}">
                <i class="material-icons prefix">settings</i>
                Settings
            </a>
        </li>
        <li>
            <a class="{% if 'logout' in url %}active{% endif %}" href="{{ url_for('admin.logout') }}">
                <i class="material-icons prefix">exit_to_app</i>
                LogOut</a>
        </li>
    </ul>
</div>

templates/includes/slider.html
<div class="slider center col s12" id="main-slider">
    <div class="slider__wrapper">
        <div class="slider__items">
            {% for item in slider %}
            <div class="slider__item">
                <img class="responsive-img" src="{{ url_for('static', filename=item['image']) }}"
                    alt="Slider image {{ loop.index }}">
                <div class="slider__item_title">
                    <h2>
                        {{ info['language'][g.locale]['name'] }}
                    </h2>
                    <span>{{ item['language'][g.locale]['text'] }}</span>
                    <div>
                        <a href="{{ url_for('website.delivery') }}">
                            <button class="btn col s6">{{ _('Замовити на доставку') }}</button>
                        </a>
                        <a class="modal-trigger" href="#modal_reserve">
                            <button class="btn col s6">{{ _('Забронювати стіл') }}</button>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>